---
title: "HW1-flux"
author: "Anwesha Bhattacharyya"
date: "September 18, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## PBS script used
```
####  PBS preamble
#PBS -N hw1
#PBS -m abe
#PBS -M anwebha@umich.edu

#PBS -j oe

#PBS -l nodes=1:ppn=5,mem=1gb,walltime=15:00
#PBS -V
#PBS -t 1-2

#PBS -A stats700f17_flux
#PBS -q flux
####  End PBS preamble

#  Show list of CPUs you ran on, if you're running under PBS
if [ -n "$PBS_NODEFILE" ]; then cat $PBS_NODEFILE; fi

#  Change to the directory you submitted from
if [ -n "$PBS_O_WORKDIR" ]; then cd $PBS_O_WORKDIR; fi
pwd

#  Put your job commands after this line
R CMD BATCH --vanilla  hw1-${PBS_ARRAYID}.R hw1-${PBS_ARRAYID}.out
```
The flux command used is qsub hw1.pbs which is the pbs script used. 

## R scripts used

hw1-1 script is as follows

```{r}
data = read.table("banknote.txt", sep = ",")
n = dim.data.frame(data)[1]
class = data$V5
table(class)
variance = data[,1]; skewness = data[,2]; kurtosis = data[,3]; entropy = data[,4]
pdf("histogram.pdf")

par(mfrow = c(2,2))
hist(variance);hist(skewness);hist(kurtosis); hist(entropy)
dev.off()

write.table(summary(cbind(variance,skewness,kurtosis,entropy,class)),"summary.txt")
pdf("corplot.pdf")
library(corrplot)
corrplot(corr = cor(cbind(variance,skewness,kurtosis,entropy)))
dev.off()

pdf("variance.pdf")
par(mfrow = c(2,2))
plot(data[,1],data[,1],col = c("darkblue","cyan")[data[,5]+1], xlab = "variance", ylab  = "variance")
plot(data[,1],data[,2],col = c("darkblue","cyan")[data[,5]+1], xlab = "variance", ylab = "skewness")
plot(data[,1],data[,3],col = c("darkblue","cyan")[data[,5]+1], xlab = "variance", ylab = "kurtosis")
plot(data[,1],data[,4],col = c("darkblue","cyan")[data[,5]+1], xlab = "variance", ylab = "entropy")
dev.off()

pdf("skewness.pdf")
par(mfrow = c(1,3))
plot(data[,2],data[,2],col = c("darkblue","cyan")[data[,5]+1], xlab = "skewness", ylab = "skewness")
plot(data[,2],data[,3],col = c("darkblue","cyan")[data[,5]+1], xlab = "skewness", ylab = "kurtosis")
plot(data[,2],data[,4],col = c("darkblue","cyan")[data[,5]+1], xlab = "skewness", ylab = "entropy")
dev.off()

pdf("kurtosis.pdf")
par(mfrow = c(1,2))
plot(data[,3],data[,3],col = c("darkblue","cyan")[data[,5]+1], xlab = "kurtosis", ylab = "kurtosis")
plot(data[,3],data[,4],col = c("darkblue","cyan")[data[,5]+1], xlab = "kurtosis", ylab = "entropy")
dev.off()

pdf("entropy.pdf")
plot(data[,4],data[,4],col = c("darkblue","cyan")[data[,5]+1], xlab = "entropy", ylab = "entropy")
dev.off()
```

The second script marked hw1-2 is given as
```{r}
data = read.table("banknote.txt", sep = ",")
n = dim.data.frame(data)[1]
class = data$V5
table(class)
variance = data[,1]; skewness = data[,2]; kurtosis = data[,3]; entropy = data[,4]


sink("output.txt")
gl = glm(class ~ variance +skewness + kurtosis + entropy - 1,  family = "binomial")
summary(gl);
pred = gl$fitted.values; pred = round(pred)
errsq = sum((pred - class)^2)/n; errsq
table(class,pred)

gl = glm(class ~ variance +skewness + kurtosis + entropy ,  family = "binomial")
summary(gl);
pred = gl$fitted.values; pred = round(pred)
errsq = sum((pred - class)^2)/n; errsq
table(class,pred)

```
##Process time
For the first script we have
```
proc.time()
user  system elapsed 
0.269   0.040   3.406 
```

For the second script we have
```
proc.time()
user  system elapsed 
0.208   0.024   0.342 
```

